#INITIAL SETTINGS
kernel_size: 5
period: 24       # Khoảng cách giữa các chu kỳ
chrono_cycle_factor: 7 # = input/period: Bao nhiêu chu kỳ quá khứ được sử dụng
nb_filters: 16  # Số lượng filter trong mỗi kernal mask
nb_stacks: 2 # Số lượng Block trong mô hình, minimum=1
input_width: 168
output_length: 1 # predict 1 hour
train_ratio: 0.9
epochs: 50
features: [ "20"]  # Features to use for training
prediction_feature: "20"  # Feature to use for prediction
overlap: True # Preprocessing input with Overlap các chu kỳ (if True, span gap = 1)
optimizer: "adam"
metrics: [ 'mse', 'mae', 'MAPE']